<?php
/**
 * CM Business Directory about page
 *
 * @author CreativeMinds (https://www.cminds.com)
 * @copyright Copyright (c) 2012, CreativeMinds
 * @package BusinessDirectory/View
 */
?>
<br />
<br />

This plugin was developed by <a href="https://www.cminds.com/" target="_blank">CreativeMinds</a>. You can find more information about the CM Business Directory <a href="https://www.cminds.com/wordpress-plugins-library/purchase-cm-business-directory-plugin-for-wordpress/" target="new">here</a>
<br /><br />
<h3>Premium Plugins by CreativeMinds</h3>
<div><a href="https://www.cminds.com/wordpress-plugins/?showfilter=No&cat=Plugin">List of Our Premium Plugins</a></div>

<br />
<h3>We Are Experts in Custom Plugin Development</h3>
<ul>
    <li><strong>Professional Quality Work </strong>- We follow a detailed coding standard that ensures we deliver only the highest quality business and services. You can count on maintainable code that fulfills your requirements completely.</li>
    <li><strong>Expert Knowledge </strong>- Custom WordPress plugins are our specialty. We devote a lot of work and time for testing to deliver to our customers bug free business. We use WP custom functions and we excel in PHP / SQL / JavaScript and related technologies like JQuery or Ajax</li>
    <li><strong>Integration with 3rd-party Plugins</strong>- Upon request we integrate our plugins with external 3-rd party tools and services such as GoToMeeting, Vimeo, Google and many others.</li>
    <li><strong>Fixed Price Quotes </strong>- We provide fixed price quotes so you know exactly what your total and final development cost will be.</li>
    <li><strong>Support and Warranty </strong>- Once your plugin is completed we will not leave you out in the cold. We believe that your success is our success and we want happy customers who will use our business again. </li>
</ul>