<div class="clear"></div>
<hr>

<h1>
    <strong><?php echo CMBD_NAME; ?> Version</strong>
</h1>

<p>
    If you like the <?php echo CMBD_NAME; ?>  but you're missing some features, probably you can find it in the Premium version.
    <br/>
    We have prepared lists of features which you can find in one of the Premium versions of <a title="<?php echo CMBD_NAME; ?>" href="<?php echo CMBD_RELEASE_NOTES; ?>"><?php echo CMBD_NAME; ?></a>.
</p>

<div class="clear"></div>

<style type="text/css">
    .column{float: left; max-width: 30%; min-width: 510px; padding: 0 1%;}
    .column.first{padding-left: 0}
    .column ul li{margin-bottom: 15px}
    .new-item:before{
        content: 'New';
        background-color: #669834;
        padding: 8px;
        font-weight: bold;
        color: #FFF;
        float: left;
        margin-right: 5px;}
    .column p{
        font-weight: bold;
        padding: 5px 0;
        font-size: 16px;
        border-bottom: 1px solid #BBB;
    }
</style>

<div class="column first">
    <h2><?php echo CMBD_NAME; ?> Pro Edition <a href="<?php echo CMBD_RELEASE_NOTES; ?>" class="button button-primary">Buy</a></h2>
    <p>Includes all Free edition features + the following:</p>
    <ul>
        <li><strong>Import / Export</strong> - Import and Export your Business items file to and from .CSV format.</li>
        <li><strong>Custom CSS</strong> - The Pro edition allows you to add the Custom CSS</li>
        <li><strong>Business Directory Views</strong> - The Pro edition allows you to display the your Business Directory on three different ways</li>
        <li><strong>Additional Custom Fields</strong> - Pro version has the ability to add additional custom fields.</li>
        <li><strong>Permalink</strong> - Pro version allows you to change the permalink of your business pages.</li>
        <li><strong>More Styling Options</strong> - Ability to change the colors of various elements of the Business Page</li>
        <li><strong>Google Maps</strong> - The <?php echo CMBD_NAME; ?> Pro edition includes an integration with the Google Maps.</li>
        <li><strong>Related Business</strong> - In the <?php echo CMBD_NAME; ?> Pro you can display related businesses on Business Page.</li>
        <li><strong>Advertisements</strong> - Pro version allows you to display advertisements on Business Pages (eg. Google Adsense).</li>
        <li><strong>Search</strong> - Instead of having just filtering, Pro edition allows to search the Business Directory</li>
        <li><strong>Labels</strong> - Ability to change all of the labels</li>
        <li><strong>Tags</strong> - The Pro version has the ability to add also tags next to the categories.</li>
        <li><strong>Ordering</strong> - The Pro version allows you to change the ordering of the Businesses in the directory.</li>
    </ul>
</div>

<div class="clear"></div>