<div class="onlyinpro" style="margin:1em 0;">
	Available in Pro version and above.
	<a href="<?php echo get_site_url(); ?>/wp-admin/admin.php?page=cmbd_pro">UPGRADE NOW&nbsp;➤</a>
</div>
<?php
/*
$labelsByCategories = CMBD_Labels::getLabelsByCategories();
foreach($labelsByCategories as $category => $labels):
    ?>
    <table>
        <caption><?php echo esc_html(empty($category) ? 'Other' : $category); ?></caption>
        <?php
        foreach($labels as $key):

            if( $default = CMBD_Labels::getDefaultLabel($key) ) :
                ?>

                <tr valign="top">
                    <th scope="row" valign="middle" align="left" >"<?php echo esc_html($default) ?>" label:</th>
                    <td>
                        <input type="text" size="60" name="label_<?php echo esc_attr($key); ?>" value="<?php echo esc_attr(CMBD_Labels::getLabel($key)); ?>" placeholder="<?php echo esc_attr($default) ?>"/>
                    </td>
                    <td><?php echo CMBD_Labels::getDescription($key); ?></td>
                </tr>

        <?php endif; ?>
        <?php endforeach; ?>
    </table>
<?php
endforeach;
*/
?>