<?php
$postId			 = $business->ID;
$mainDivClass	 = 'cmbd-module-actions';
$imageEdge		 = array();

$height = CMBD_Settings::getOption( CMBD_Settings::OPTION_BUSINESS_HEIGHT );
if ( !empty( $height ) && is_numeric( $height ) ) {
	$height .= 'px';
}
$customHeight		 = !empty( $height ) ? 'height: ' . $height : null;
$customStyleArr[]	 = $customHeight;

$width = CMBD_Settings::getOption( CMBD_Settings::OPTION_BUSINESS_WIDTH );
if ( !empty( $width ) && is_numeric( $width ) ) {
	$width .= 'px';
}

if ( is_numeric( intval( $width ) ) ) {
	$imageEdge[] = intval( $width );
}
if ( is_numeric( intval( $height ) ) ) {
	$imageEdge[] = intval( $height );
}

if ( !empty( $imageEdge ) ) {
	/*
	 * calculate the image width
	 */
	if ( !is_array( $imageEdge ) ) {
		$imageEdge = array( $imageEdge );
	}
	$imageEdge	 = min( $imageEdge );
	$sizeArray	 = array( $imageEdge, $imageEdge );
} else {
	$sizeArray = null;
}

$customWidth		 = !empty( $width ) ? 'width: ' . $width : null;
$customStyleArr[]	 = $customWidth;
$setting			 = CMBD_Settings::getOption( CMBD_Settings::OPTION_BUTTONS_TARGET_BLANK );
$blank				 = empty( $setting ) ? '' : 'target="_blank" ';
$customStyle		 = implode( ';', array_filter( $customStyleArr ) );
$setting2			 = CMBD_Settings::getOption( CMBD_Settings::OPTION_BUTTONS_BUSINES_PITCH_IMG );
$business_pith		 = '';
if ( !empty( $setting2 ) ) {
	$business_pith	 = CMBusinessDirectory::meta( $postId, 'cmbd_business_pitch' );
	$business_pith	 = strip_tags( $business_pith );
	$business_pith	 = substr( $business_pith, 0, 300 );
}
/*
 * Added the custom size
 */
$image = CMBusinessDirectoryBusinessPage::getBusinessGallery( $business->ID, $sizeArray );

$default_image	 = CMBD_Settings::getOption( CMBD_Settings::OPTION_BUSINESS_DEFAULT_IMAGE );
$default_image	 = empty( $default_image ) ? CMBD_PLUGIN_URL . 'frontend/assets/img/blank_business.png' : $default_image;

$url	 = !empty( $image[ 0 ][ 'cmbd_image_custom' ][ 0 ] ) ? $image[ 0 ][ 'cmbd_image_custom' ][ 0 ] : (!empty( $image[ 0 ][ 'cmbd_image' ][ 0 ] ) ? $image[ 0 ][ 'cmbd_image' ][ 0 ] : $default_image);
$title	 = $business->post_title;

$view = 'directory-view';
?>

<div class="product-related cmbd-directory" style="<?php echo esc_attr( $customStyle ); ?>; float:left;">
    <a href="<?php echo esc_attr( get_permalink( $business->ID ) ); ?>" <?php echo $blank ?>>
        <div class="cmbd_inside">
			<?php if ( !empty( $url ) ) : ?>
				<img class="img_center the_image" alt="<?php echo esc_attr( $title ); ?>" <?php echo!empty( $imageEdge ) ? 'width="' . $imageEdge . '"' : ''; ?> <?php echo!empty( $imageEdge ) ? 'height="' . $imageEdge . '"' : ''; ?> src="<?php echo esc_attr( $url ); ?>" title="<?php echo $business_pith; ?>" style="width:100%;" />
			<?php else: ?>
				<img class="img_center the_image" src="<?php echo CMBD_PLUGIN_URL . 'frontend/assets/img/blank_business.png'; ?>" alt="<?php echo esc_attr( $title ); ?>" title="<?php echo $business_pith; ?>" style="width:100%;" />
			<?php endif; ?>
            <h5 class="connected-title text-center cmbd-directory-title"><?php
				echo $title;
				?>
            </h5>
        </div>
    </a>
	<?php echo CMBusinessDirectoryFrontend::outputEditlink( $business, $atts ); ?>
</div>

